### ISSUE TITLE
Running FHMM with modified REDD dataset.

### ISSUE THREAD

**Issue by BowonY** [nilmtk/nilmtk#348]
Hi, I'm trying to run fhmm_exact in co_fhmm.ipynb. I had memory problem to run building 1 in REDD.
So I downsized the dataset of building 1 from 20 dat files to 5 with the modified building1.yaml file.
But I this time I had another value error.

First, this is the building1.yaml file.
```
instance: 1   # this is the first building in the dataset
original_name: house_1   # original name from REDD dataset
elec_meters:
  1: &redd_whole_house 
    site_meter: true
    device_model: REDD_whole_house
  2: *redd_whole_house
  3: &emonitor
    submeter_of: 0 
    device_model: eMonitor
  4: *emonitor
  5: *emonitor

appliances:
- original_name: oven
  type: electric oven
  instance: 1
  meters: [3, 4]   # draws power from both 120 volt legs

- original_name: refrigerator
  type: fridge
  instance: 1
  meters: [5]

```

This is the part of co_fhmm.ipynb:
```python
# Disaggregate
disag_filename = join(data_dir, 'redd-disag-fhmm.h5')
output = HDFDataStore(disag_filename, 'w')
fhmm.disaggregate(elec.mains(), output)
output.close()
```

This is the error messages:
```
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-94ad9417907f> in <module>()
      2 disag_filename = join(data_dir, 'redd-disag-fhmm.h5')
      3 output = HDFDataStore(disag_filename, 'w')
----> 4 fhmm.disaggregate(elec.mains(), output)
      5 output.close()

/home/narae/nilmtk/nilmtk/disaggregate/fhmm_exact.py in disaggregate(self, mains, output_datastore, **load_kwargs)
    372 
    373             # Start disaggregation
--> 374             predictions = self.disaggregate_chunk(chunk)
    375             for meter in predictions.columns:
    376 

/home/narae/nilmtk/nilmtk/disaggregate/fhmm_exact.py in disaggregate_chunk(self, test_mains)
    263         length = len(test_mains.index)
    264         temp = test_mains.values.reshape(length, 1)#fix
--> 265         learnt_states_array.append(self.model.predict(temp))
    266 
    267 

/home/narae/anaconda/lib/python2.7/site-packages/hmmlearn/base.pyc in predict(self, obs, algorithm)
    281             Index of the most likely states for each observation
    282         """
--> 283         _, state_sequence = self.decode(obs, algorithm)
    284         return state_sequence
    285 

/home/narae/anaconda/lib/python2.7/site-packages/hmmlearn/base.pyc in decode(self, obs, algorithm)
    264         decoder = {"viterbi": self._decode_viterbi,
    265                    "map": self._decode_map}
--> 266         logprob, state_sequence = decoder[algorithm](obs)
    267         return logprob, state_sequence
    268 

/home/narae/anaconda/lib/python2.7/site-packages/hmmlearn/base.pyc in _decode_viterbi(self, obs)
    197         """
    198         obs = np.asarray(obs)
--> 199         framelogprob = self._compute_log_likelihood(obs)
    200         viterbi_logprob, state_sequence = self._do_viterbi_pass(framelogprob)
    201         return viterbi_logprob, state_sequence

/home/narae/anaconda/lib/python2.7/site-packages/hmmlearn/hmm.pyc in _compute_log_likelihood(self, obs)
    183     def _compute_log_likelihood(self, obs):
    184         return log_multivariate_normal_density(
--> 185             obs, self._means_, self._covars_, self._covariance_type)
    186 
    187     def _generate_sample_from_state(self, state, random_state=None):

/home/narae/anaconda/lib/python2.7/site-packages/sklearn/mixture/gmm.pyc in log_multivariate_normal_density(X, means, covars, covariance_type)
     57         'full': _log_multivariate_normal_density_full}
     58     return log_multivariate_normal_density_dict[covariance_type](
---> 59         X, means, covars)
     60 
     61 

/home/narae/anaconda/lib/python2.7/site-packages/sklearn/mixture/gmm.pyc in _log_multivariate_normal_density_full(X, means, covars, min_covar)
    603                                       lower=True)
    604         cv_log_det = 2 * np.sum(np.log(np.diagonal(cv_chol)))
--> 605         cv_sol = linalg.solve_triangular(cv_chol, (X - mu).T, lower=True).T
    606         log_prob[:, c] = - .5 * (np.sum(cv_sol ** 2, axis=1) +
    607                                  n_dim * np.log(2 * np.pi) + cv_log_det)

/home/narae/anaconda/lib/python2.7/site-packages/scipy/linalg/basic.pyc in solve_triangular(a, b, trans, lower, unit_diagonal, overwrite_b, debug, check_finite)
    152 
    153     if check_finite:
--> 154         a1, b1 = map(np.asarray_chkfinite,(a,b))
    155     else:
    156         a1, b1 = map(np.asarray, (a,b))

/home/narae/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.pyc in asarray_chkfinite(a, dtype, order)
    611     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
    612         raise ValueError(
--> 613             "array must not contain infs or NaNs")
    614     return a
    615 

ValueError: array must not contain infs or NaNs

```

And please tell me how to run fhmm with original REDD dataset on my computer with 8G memory if possible.

Thank you.
