### ISSUE TITLE
Metadata questions - meter definition

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#392]
I have attempted to write the metadata for my meter, below is the contents of meter_devices.yaml
The comments by the physical_quantity tags describe what can be retrieved from the meter display.
Questions:
1. The first two describe cumulative figures since the meter clamp was powered up, and are now big numbers hence the high limit - is this right and should these be energy?
2. The samples have different time granularities (see comments) I have used the finest to set the max sample period, although this is a guess- is this right?
3. Reactive power data contains negative numbers, should the lower_limit figure be different from 0?

```yaml
ED01013:
  model: ED01013
  manufacturer: Onzo Ltd
  manufacturer_url: http://www.onzo.com/
  description: Multifunction whole house meter and home display
  sample_period: 1 # the interval between samples. In seconds.
  max_sample_period: 300 # Max allowable interval between samples. Seconds.
  measurements:
  - physical_quantity: energy   #energy low res - cumulative energy use every 35 minutes approximately
    type: active   # active (real power), reactive or apparent?
    upper_limit: 10000000
    lower_limit: 0
  - physical_quantity: energy   #energy high res - cumulative energy use every 10 minutes approximately
    type: active   # active (real power), reactive or apparent?
    upper_limit: 10000000
    lower_limit: 0
  - physical_quantity: power   #power real standard - power granularity < 30 Seconds
    type: apparent   # active (real power), reactive or apparent?
    upper_limit: 10000
    lower_limit: 0
  - physical_quantity: power   #power real fine - power granularity  1 Second (no data if no change)
    type: apparent   # active (real power), reactive or apparent?
    upper_limit: 10000
    lower_limit: 0
  - physical_quantity: power   #power reactive standard granularity  1 Second (no data if no change)
    type: reactive   
    upper_limit: 10000
    lower_limit: 0
```
