### ISSUE TITLE
Test my own Meter Data...

### ISSUE THREAD

**Issue by caxefaizan** [nilmtk/nilmtk#897]
I have my own aggregated meter data and want to see how the NILMTK performs... I want the TK to show the air conditioner consumption. So technically i have only one meter which has generated a table of data for almost 1.5 hrs.. However i'm facing problem with converting it to REDD data format. It seems there is some issue in meta data. 

 
![image](https://user-images.githubusercontent.com/63395276/93978639-e6123d00-fd99-11ea-817d-371b83f3418c.png)

This is the building1.yaml
![image](https://user-images.githubusercontent.com/63395276/93978771-1954cc00-fd9a-11ea-8dbc-0693f4dc6708.png)

This is the meter_devices.yaml
![image](https://user-images.githubusercontent.com/63395276/93978837-2ec9f600-fd9a-11ea-8000-e4f1c7a1ad74.png)

**Comment by levaphenyl** [comment]
`device_model` is an attribute of the `ElecMeter` class and not of the `Building` class, as documented in [nilm-metadata](https://nilm-metadata.readthedocs.io/en/latest/dataset_metadata.html#elecmeter).
I suggest you fix your `meter_devices.yaml`.

**NB:** When sharing text files or code, please don't upload screenshots but use the "Insert code" button! Nobody will take the effort to re-type your code...

**Comment by caxefaizan** [comment]
> `device_model` is an attribute of the `ElecMeter` class and not of the `Building` class, as documented in [nilm-metadata](https://nilm-metadata.readthedocs.io/en/latest/dataset_metadata.html#elecmeter).
> I suggest you fix your `meter_devices.yaml`.
> 
> **NB:** When sharing text files or code, please don't upload screenshots but use the "Insert code" button! Nobody will take the effort to re-type your code...

Point taken for screenshots... However i created the metadata by by comparing with REDD data and iawe data.
`eMonitor:
  model: eMonitor
  manufacturer: Powerhouse Dynamics
  manufacturer_url: http://powerhousedynamics.com
  description: >
    Measures circuit-level power demand.  Comes with 24 CTs.
    This FAQ page suggests the eMonitor measures real (active)
    power: http://www.energycircle.com/node/14103  although the REDD
    readme.txt says all channels record apparent power.
  sample_period: 3   # the interval between samples. In seconds.
  max_sample_period: 50   # Max allowable interval between samples. Seconds.
  measurements:
  - physical_quantity: power   # power, voltage, energy, current?
    type: active   # active (real power), reactive or apparent?
    upper_limit: 5000
    lower_limit: 0
  wireless: false`
and also the buildings
`instance: 1   # this is the first building in the dataset
original_name: house_1   # original name from REDD dataset
elec_meters:
  1: &redd_whole_house 
    site_meter: true
    device_model: REDD_whole_house
  2: *redd_whole_house
  3: &emonitor
    submeter_of: 0 
    device_model: eMonitor`

**Comment by levaphenyl** [comment]
There is a YAML syntax error in `building1.yaml`. The special character `&` is only used if you want to repeat the value. By using `&minion` you are overwriting the `minion` object. Since you have only one meter, you can remove the reference. See [YAML syntax](https://yaml.org/refcard.html).

Is it better when using the following for `building1.yaml`?
```yaml
elec_meters:
    1:
        site_meter: true
        device_model: minion
```

Hint: to make code blocks in markdown, use the triple backquote (```).

**Comment by caxefaizan** [comment]
Thanks for the codeblock hint 🥇  
I changed the buildings1.yaml as 
```
instance: 1 # this is the first building in the dataset
elec_meters: # a dictionary where each key is a meter instance
  1: 
    site_meter: true # meter 1 measures the whole-building aggregate
    device_model: minion
```

and the meter_devices.yaml as:

```
minion:
  description: >
    Mains Data Capture
  sample_period: 1
  max_sample_period: 1
  measurements:
  - physical_quantity: power   
    type: active   
    upper_limit: 10000
    lower_limit: 0
  - physical_quantity: power
    type: apparent
    upper_limit: 10000
    lower_limit: 0
  - physical_quantity: power
    type: reactive
    upper_limit: 10000
    lower_limit: 0
  - physical_quantity: frequency  
    type: 
    upper_limit: 70
    lower_limit: 0
  - physical_quantity: voltage 
    type: 
    upper_limit: 270
    lower_limit: 0
  - physical_quantity: current  
    type:  
    upper_limit: 100
    lower_limit: 0
```

Now this is the error i'm getting. 
```
KeyError                                  Traceback (most recent call last)
<ipython-input-608-4262b0185780> in <module>()
     63 store.close()
     64 
---> 65 convert_yaml_to_hdf5('./metadata', output_filename)
     66 
     67 print("Done converting iAWE to HDF5!")

C:\Users\Faizan\anaconda3\envs\nilmtk-env\lib\site-packages\nilm_metadata\convert_yaml_to_hdf5.py in convert_yaml_to_hdf5(yaml_dir, hdf_filename)
     54         _set_data_location(elec_meters, building)
     55         _sanity_check_meters(elec_meters, meter_devices)
---> 56         _sanity_check_appliances(building_metadata)
     57         group._f_setattr('metadata', building_metadata)
     58 

C:\Users\Faizan\anaconda3\envs\nilmtk-env\lib\site-packages\nilm_metadata\convert_yaml_to_hdf5.py in _sanity_check_appliances(building_metadata)
    147     * Make sure there aren't multiple appliance types with same instance
    148     """
--> 149     appliances = building_metadata['appliances']
    150     appliance_types = get_appliance_types()
    151     building_instance = building_metadata['instance']

KeyError: 'appliances'
```
